#!/usr/bin/env node
// Writes assets/js/modules/city-areas.js: the areas the homepage search offers for every city except Rishikesh (whose
// list is AREAS in data.js, the filter of /homestays). Read from the built stays data modules (stays-index-data.js =
// Rishikesh, stays-index-data-<city>.js), most stays first, areas with at least 3 stays. Run by `npm run build:stays`
// (and by hand: node scripts/stays/city_areas.mjs) after the data modules are rebuilt. Never hand-edit the output.
import { readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const MODULES = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', 'assets', 'js', 'modules');
const MIN_STAYS = 3, MAX_AREAS = 14;

const out = {};
for (const f of readdirSync(MODULES).sort()) {
  const m = /^stays-index-data-([a-z]+)\.js$/.exec(f);
  if (!m) continue; // the Rishikesh module has no city suffix and is not written (AREAS in data.js)
  const { STAYS_INDEX } = await import(pathToFileURL(path.join(MODULES, f)).href);
  const count = {};
  for (const d of STAYS_INDEX) if (d.a && !/^Elsewhere/i.test(d.a)) count[d.a] = (count[d.a] || 0) + 1;
  out[m[1]] = Object.entries(count).filter(([, n]) => n >= MIN_STAYS).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, MAX_AREAS).map(([a]) => a);
}
const body = `// Generated by scripts/stays/city_areas.mjs from the stays data modules (npm run build:stays). Do not edit.\n`
  + `// The homepage search's Area list for each city but Rishikesh (Rishikesh uses AREAS in data.js).\n`
  + `export const CITY_AREAS = ${JSON.stringify(out, null, 2)};\n`;
writeFileSync(path.join(MODULES, 'city-areas.js'), body);
console.log('city-areas.js:', Object.entries(out).map(([c, a]) => `${c} ${a.length}`).join(', '));
